name: validate-openapi

on:
  push:
    branches: [ main ]
    
jobs:
  Validate-OpenAPI-Descriptions:
    runs-on: ubuntu-latest
    container:
      image: redocly/openapi-cli
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3 # checkout repo content
      - name: Validate monopad-ada-1.0.yml
        run: openapi lint --apis=$GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/monopad-ada-1.0.yml
